/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecart.eps2oop;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gunam
 */
public class IndexPerpustakaan extends javax.swing.JFrame {

    public Statement statement;
    public ResultSet result;
    Connection connection = DBConnection.OpenConnection();

    /**
     * Creates new form IndexPerpustakaan
     *
     * @throws java.sql.SQLException
     */
    public IndexPerpustakaan() throws SQLException {
        initComponents();
        showBooks("", "");
    }

    private void showBooks(String searchTerm, String query) {
        try {
            statement = connection.createStatement();
            if ("".equals(searchTerm)) {
                result = statement.executeQuery("SELECT * FROM buku LIMIT 10");
            } else {
                result = statement.executeQuery("SELECT * FROM buku WHERE " + searchTerm + " LIKE '%" + query + "%';");
            }

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Buku");
            model.addColumn("Judul");
            model.addColumn("Penulis Buku");
            model.addColumn("Tahun Terbit");
            model.addColumn("Deskripsi");
            model.addColumn("Edit");
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            boolean hasData = false;
            while (result.next()) {
                hasData = true;
                Object[] data = {
                    result.getString("id_buku"),
                    result.getString("judul_buku"),
                    result.getString("penulis_buku"),
                    result.getString("tahun_terbit"),
                    result.getString("deskripsi"),
                    "Edit"
                };
                model.addRow(data);
            }

            if (!hasData) {
                model.setRowCount(0);
            }

            dataTable.setModel(model);
            dataTable.getColumn("Edit").setCellRenderer(new ButtonRenderer());
            dataTable.getColumn("Edit").setCellEditor(new ButtonEditor(this));
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        btnCreateBook = new javax.swing.JButton();
        cmbSearch = new javax.swing.JComboBox<>();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerPage.setText("List Buku Perpustakaan TecArt");
        getContentPane().add(bannerPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 160, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 630, -1));

        btnCreateBook.setText("Create Book");
        btnCreateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul Buku", "Penulis", "Deskripsi", "Tahun Terbit" }));
        getContentPane().add(cmbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });
        getContentPane().add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 350, -1));

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel1.setText("Cari Buku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBookActionPerformed
        new CreateBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateBookActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (cmbSearch.getSelectedItem() == "Judul Buku") {
            showBooks("judul_buku", inputSearch.getText());
        } else if (cmbSearch.getSelectedItem() == "Penulis") {
            showBooks("penulis_buku", inputSearch.getText());
        } else if (cmbSearch.getSelectedItem() == "Deskripsi") {
            showBooks("deskripsi", inputSearch.getText());
        } else if (cmbSearch.getSelectedItem() == "Tahun Terbit") {
            showBooks("tahun_terbit", inputSearch.getText());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new IndexPerpustakaan().setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex);
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerPage;
    private javax.swing.JButton btnCreateBook;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
